/**
* @author exia.huang
* @homepage http://salesforcexytools.com
*/
@isTest
private class BillExtensionTest {

    /**
     * This is a test method for queryBill
     */
    static testMethod void test_queryBill() {

        // PageReference pageRef = Page.MyBillPage;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('language', '');

        Test.startTest();

        String para1 = '';
        //Object result_queryBill = BillExtension.queryBill(para1);

        Test.stopTest();

    }

}