/**
* @author exia.huang
* @homepage http://salesforcexytools.com
*/
@isTest
private class InfoRecordControllerTest {

    /**
     * This is a test method for saveAction
     */
    static testMethod void test_saveAction() {

        // PageReference pageRef = Page.undefined;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('param1', 'param1');

        Test.startTest();

        // InfoRecordController obj = new InfoRecordController();
        // PageReference result_saveAction = obj.saveAction();

        Test.stopTest();

        // Check
        // System.assert(ApexPages.hasMessages());
        // for(ApexPages.Message msg : ApexPages.getMessages()) {
        //     System.assertEquals('Upload file is NULL', msg.getSummary());
        //     System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
        // }
    }


    /**
     * This is a test method for cancelAction
     */
    static testMethod void test_cancelAction() {

        // PageReference pageRef = Page.undefined;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('param1', 'param1');

        Test.startTest();

        // InfoRecordController obj = new InfoRecordController();
        // PageReference result_cancelAction = obj.cancelAction();

        Test.stopTest();

        // Check
        // System.assert(ApexPages.hasMessages());
        // for(ApexPages.Message msg : ApexPages.getMessages()) {
        //     System.assertEquals('Upload file is NULL', msg.getSummary());
        //     System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
        // }
    }

}