/*
    目    的：主动从SAP查询材证时，生成SAP接收参数
    作    者：刘文俊(liuwenjun@bluelinksys.com)
    创建日期：2017-06-05
    修 改 人：
    修改日期：
    修改原因：
    备    注：主动从SAP查询材证时，查询结果转化类
*/
public without sharing class SapMaterialCertificate {
    //调用成功标记：1 - 表示成功，0 - 表示失败
    public String status {GET; SET;}
    //调用描述：成功为空或相关信息，失败时为失败原因信息
    public String message {GET; SET;}
    //调用返回结果
    public List<MaterialCertificate> content {GET; SET;}

    public class MaterialCertificate {
        public String Template_Name {get; set;} //模板名称
        public String Certificate_NO {get; set;} //材证编号
        public String Customer_Name {get; set;} //客户名称
        public String Stocking_NO {get; set;} //备货单号
        public String Batch_NO {get; set;} //批次
        public String Customer_Order_NO {get; set;} //客户订单号
        public String Customer_Material_NO {get; set;} //客户料号
        public String KL_Material_NO {get; set;} //新莱料号
        public String Material_Description {get; set;} //料号描述
        public String Material_Type {get; set;} //物料类型
        public String Date_of_Certificate {get; set;} //过账日期 - 出货日期
        public String Voucher_NO {get; set;} //凭证号
        public String Quantity {get; set;} //数量
        public String Quantity_Unit {get; set;} //数量单位
        public String Order_NO {get; set;} //订单号
        public String DT_Code {get; set;} //DTCODE
        public String Job_NO {get; set;} //工单号
        public String Material_Description_EN {get; set;} //英文物料描述
        public List<HeatAnalyzeAndSpecification> heats {GET; SET;} //原材料成分
        public List<MechanicalTest> mechanicals {GET; SET;} //机械性能测试
        public List<MechanicalTestContinuation> continuations {GET; SET;} //机械性能测试
        public List<OtherAnalysisAndInspection> others {GET; SET;} //其他分析和检查
    }
    //Raw Material Heat Analyze and Specification (weight%)（原材料成分，重量%）
    public class HeatAnalyzeAndSpecification {
        public String Heat_Number {get; set;} //炉号‎
        public String C {GET; SET;}
        public String Si {GET; SET;}
        public String Mn {GET; SET;}
        public String P {GET; SET;}
        public String S {GET; SET;}
        public String Ni {GET; SET;}
        public String Cr {GET; SET;}
        public String N {GET; SET;}
        public String Mo {GET; SET;}
        public String Material_Standard {get; set;} //材料标准
        public String Raw_Material_Spec {get; set;} //物料品名
        public String Batch_NO {get; set;} //批次
    }
    //Mechanical Test‎‎‎ 机械性能测试
    public class MechanicalTest {
        public String Heat_Number {get; set;} //炉号‎
        public String Yield02 {GET; SET;} //屈服MPa
        public String Rp02 {GET; SET;} //强度KSI
        public String Yield10 {GET; SET;} //屈服MPa
        public String Rp10 {GET; SET;} //强度KSI
        public String Tensile {GET; SET;} //抗拉
        public String Strength {GET; SET;} //强度
        public String Width_of_Gage_Length {GET; SET;} //标距宽度
        public String Hardness {GET; SET;} //硬度
        public String Reduction_of_Area {GET; SET;} //断面收缩率
        public String Elongation {GET; SET;} //纵向延伸率
        public String Raw_Material_Spec {get; set;} //物料品名
        public String Batch_NO {get; set;} //批次
    }
    //Mechanical Test Continuation  机械性能测试
    public class MechanicalTestContinuation {
        public String Heat_Number {get; set;} //炉号‎
        public String Impact_Test {get; set;} //冲击试验
        public String Eddy_Current_Test {get; set;} //涡流探伤
        public String Flaring_Flange_Test {get; set;} //扩口/卷边试验
        public String Flattening_Reverse_Flattening {get; set;} //压扁和反向压扁试验
        public String Bend_Reverse_Bend_Test {get; set;} //弯曲和反向弯曲试验
        public String Intergranular_Corrosion_Test {get; set;} // per ASTM A262-E晶间腐蚀试验(ASMT A262-E)
        public String Raw_Material_Spec {get; set;} //物料品名
        public String Batch_NO {get; set;} //批次
    }
    //Other Analysis and Inspection  其他分析和检查
    public class OtherAnalysisAndInspection {
        public String Visual_Dimensional_Test {get; set;} //目检和尺寸检验
        public String Material_Identification {get; set;} //材质分析试验
        public String Ra_Max_Value {get; set;} //(ID/OD)μm内外表面粗糙度值
        public String Raw_Material_Spec {get; set;} //物料品名
        public String Batch_NO {get; set;} //批次
    }
}