/**
* @author exia.huang
* @homepage http://salesforcexytools.com
*/
@isTest
private class SiteMaterialExtensionTest {

    /**
     * This is a test method for queryMaterial
     */
    static testMethod void test_queryMaterial() {

        // PageReference pageRef = Page.undefined;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('param1', 'param1');

        Test.startTest();

        // String materialCertificateCode;
        // String materialNumber;
        // String stockingNO;
        // String contractNO;
        // String batchNO;
        // Object result_queryMaterial = SiteMaterialExtension.queryMaterial(materialCertificateCode , materialNumber , stockingNO , contractNO , batchNO);

        Test.stopTest();

        // Check
        // System.assert(ApexPages.hasMessages());
        // for(ApexPages.Message msg : ApexPages.getMessages()) {
        //     System.assertEquals('Upload file is NULL', msg.getSummary());
        //     System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
        // }
    }

}