/**
* @author exia.huang
* @homepage http://salesforcexytools.com
*/
@isTest
private class SiteUserInfoExtensionTest {

    /**
     * This is a test method for getUserInfo
     */
    static testMethod void test_getUserInfo() {

        // PageReference pageRef = Page.undefined;
        // Test.setCurrentPage(pageRef);
        // pageRef.getParameters().put('param1', 'param1');

        Test.startTest();

        // SiteUserInfoExtension obj = new SiteUserInfoExtension();
        // PageReference result_getUserInfo = obj.getUserInfo();

        Test.stopTest();

        // Check
        // System.assert(ApexPages.hasMessages());
        // for(ApexPages.Message msg : ApexPages.getMessages()) {
        //     System.assertEquals('Upload file is NULL', msg.getSummary());
        //     System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
        // }
    }

}